name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - update_documentation

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/doc/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system packages
        run: sudo apt update && sudo apt install gettext

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          pip install setuptools
        working-directory: doc   

      - name: Build documentation
        run: make html
        working-directory: doc          

      - name: Test Documentation Build
        run: |
          if [ ! -d "doc/_build/html" ]; then
            echo "Build failed: HTML directory not found."
            exit 1
          fi
        working-directory: doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/_build/html
          force_orphan: true
